### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Dragon-Flamers** [kettle017/RU_Bookmate_downloader#4]
![Screenshot_20240605_120835_Termux](https://github.com/kettle017/RU_Bookmate_downloader/assets/52756531/88a53b46-9155-4626-9407-28430bf15924)

**Comment by asaldele1** [comment]
Здравствуйте! При работе в termux получение токена прямо через интерфейс скрипта не поддерживается. Вам нужно написать токен в файл token.txt в папке с программой. Чтобы его получить запустите скрипт на компьютере, или выполните эти шаги:

1. Перейти по ссылке: https://oauth.yandex.ru/authorize?response_type=token&client_id=4483e97bab6e486a9822973109a14d05
2. Авторизоваться в аккаунт Яндекс
3. На странице "Авторизация в приложении Букмейт не удалась" скопировать токен после access_token= и до &.
