### ISSUE TITLE
Ошибка при выполнении

### ISSUE THREAD

**Issue by Dragon-Flamers** [kettle017/RU_Bookmate_downloader#5]
![Screenshot_20240808_104320_Termux](https://github.com/user-attachments/assets/a483902d-d38f-417b-8051-2002abf6587c)

Всё сделал как надо, все зависимости стоят, файл token.txt в папке не было, создал сам, токен закинул, в ошибке самая последняя строка как раз мой токен. Почему всё ещё не работает, непонятно.

**Comment by Di9** [comment]
а что за знак `b'` перед токеном? это есть в файле? токен должен начинаться с `y....`

**Comment by Dragon-Flamers** [comment]
![Uploading Screenshot_20240813_112420_Termux.png…]()

**Comment by Dragon-Flamers** [comment]
![Screenshot_20240813_112420_Termux](https://github.com/user-attachments/assets/f1821596-021d-4903-9af4-83c28626479d)

Всё там в порядке, никакого b' там нет

**Comment by Dragon-Flamers** [comment]
При редактирования/создание файла через nano почему-то появляется как раз эта b'

**Comment by Dragon-Flamers** [comment]
![Screenshot_20240814_082751_Termux](https://github.com/user-attachments/assets/05209629-24bb-462a-9848-05a5f09a7178)
Но теперь появилась другая ошибка.

**Comment by zaxari1** [comment]
А где взять этот токен? И почему в инструкции этого нет.

**Comment by Dragon-Flamers** [comment]
Не знаю что случилось, но я просто всё переустановил заново и оно заработало! Для меня вопрос закрыт, остальным могу посоветовать только переустановить данную программу.
